### ISSUE TITLE
App Icon for start screen iOS not nice

### ISSUE THREAD

**Issue by eppoedzes** [swttt/com.swttt.homeydash#16]
For of all, very nice work!

When I made a App bookmark for my start screen from safari, the resulting App Icon is not nice.
![img_0159](https://cloud.githubusercontent.com/assets/19475932/21622262/f0bd1fda-d1fc-11e6-88e0-91dca5fdc759.PNG)

**Comment by swttt** [comment]
Oh indeed, totally forgot about it! :) will add this in 0.0.2

Thanks!

**Comment by eppoedzes** [comment]
👍

**Comment by swttt** [comment]
Fixed in 0.0.2

**Comment by swttt** [comment]
By the way, will add nice icons later. Need to edit most of the graphics.
