### ISSUE TITLE
Device toevoegen na delete van pagina 

### ISSUE THREAD

**Issue by Fire69** [swttt/com.swttt.homeydash#17]
Als je een pagina maakt, die dan selecteert en dan die pagina delete, blijft het plusje staan om een device toe te voegen.
Als je erop klikt krijg je het venstertje om device toe te voegen bij niet-bestaande pagina.
Als je probeert op te slaan, lukt dit niet.

**Comment by swttt** [comment]
Fixed in 0.0.4
