### ISSUE TITLE
Non-minified JS

### ISSUE THREAD

**Issue by vogon1** [swttt/com.swttt.homeydash#21]
Would you mind sharing non-minified JS code?
Makes reading, bug fixing and extending functionality a lot easier.

**Comment by swttt** [comment]
Code can be found here, and will be updated every appstore release.
https://github.com/swttt/homeydash-v3

I am using yeoman for the scaffolding with angular generator that use grunt to run local (need to change url's on the next update) or use grunt to create a production version and put it in the www folder of the app :)
