### ISSUE TITLE
Compatibility with iPad 1

### ISSUE THREAD

**Issue by Timvdv** [swttt/com.swttt.homeydash#28]
Hey @swttt!

I wanted to try getting the the app working on a iPad1 but then I saw that only the compiled code of the dashboard is committed to Github. This way I can't help you with the project. 

The error I get on the iPad1 is: `failed to instantiate module ng ...`.
Same thing when I try this in the Chrome browser on iPad1.

The fix could be as simple as changing the loading order (load angular first before the other apps). But I have no idea because I can't see the pre-build code.

Tim 

*edit* I found: https://github.com/swttt/HomeDash_v2 is this the code?

**Comment by swttt** [comment]
Hi Tim,

You can find the code here https://github.com/swttt/homeydash-v3/blob/master/app/index.html

This isnt up2date with the current local version. I will look at fixing the last bugs tonight and update it.

By the way, Angular is loaded 2nd just after jquery. So that shouldnt be the issue....

**Comment by Timvdv** [comment]
Cool! Just fixed the issue for the iPad1. Just add this shim before angular is loaded and it will also work on the iPad1.

```
if (typeof Function.prototype.bind != 'function') {
    Function.prototype.bind = function bind(obj) {
        var args = Array.prototype.slice.call(arguments, 1),
            self = this,
            nop = function() {
            },
            bound = function() {
                return self.apply(
                    this instanceof nop ? this : (obj || {}), args.concat(
                        Array.prototype.slice.call(arguments)
                    )
                );
            };
        nop.prototype = this.prototype || {};
        bound.prototype = new nop();
        return bound;
    };
}
```

**Comment by swttt** [comment]
Should be fixed when merged with the master branch
