### ISSUE TITLE
only a few device widget's showing to install.

### ISSUE THREAD

**Issue by backslashgithub** [swttt/com.swttt.homeydash#30]
don't show all off my device's :-(

using Mac Book Pro and Safari and Chrome browsers...

**Comment by swttt** [comment]
The current github verson will show all the dim, on/off and measure_temperature capable devices.
In the appstore still is version 0.0.4 that only has on/off devices.

Depending on what version you are running, it should show all the capable devices.
If this isn't the case, could you let me know what kind of devices are not showing?

**Comment by backslashgithub** [comment]
issue #30 was without al lot of device's now running in debug mode HomeyDash v0.0.5 and my problem was solved 👍 .
after running i did a install (with app athom, i got GitHub desktop to but dont know how to work it) en the app installed on my Homey. great
Only next line i dont understand, it was at the end of installing the HomeyDash v0.0.5
"DeprecationWarning: Calling an asynchronous function without callback is deprecated."

ps only my kaku ASUN-650 dont  shows up, the other device's like Sonos dont work yet with your great app. (trying to diced with ipad to by, much euro's :( i think its great for homey and your app ofcourse)

thx @swttt

**Comment by swttt** [comment]
The ASUN-650 has other capabilities then on/off or dim. So will be added later :)
