### ISSUE TITLE
when using ' in a room name the dash does not respond

### ISSUE THREAD

**Issue by B3rt** [swttt/com.swttt.homeydash#31]
I added a room called: combinatie's 

When i done this i could not add devices or even delete the room.

Using a hardcoded link in the browser i could delete the room.

It seems that the dashboard does not respond, the code seems to be working but the gui not.

**Comment by swttt** [comment]
Fixed in current alpha. Escaped all the input for page names. For now it is imposible to use the AND sign, single quotes and double qoutes. (they will get omited automatically)
