### ISSUE TITLE
homeydash keeps reloading url in browser, and dosn't start dash.

### ISSUE THREAD

**Issue by backslashgithub** [swttt/com.swttt.homeydash#32]
When i click "go to homeydash" the browser let the url with the token reload time and again, it dos not start the dash :-( (running HomeyDash v0.0.5)

![schermafbeelding 2017-02-05 om 11 23 35](https://cloud.githubusercontent.com/assets/20621496/22625403/94ffda86-eb95-11e6-8067-8030195aaa8a.png)

**Comment by swttt** [comment]
Tried to replicate this issue...i  might have left some hardcoded bearer token stuff in there by accident. Whats happens if you enable persistent bearer token in the settings?

**Comment by backslashgithub** [comment]
hey, problem solved, how i dont know. during the day tryed againa and worked. thx for your trouble!
