### ISSUE TITLE
Request - option to select an icon when adding widgets

### ISSUE THREAD

**Issue by Spaapen** [swttt/com.swttt.homeydash#34]
It would be a nice feature to be able to select (or to upload) an icon when adding a widget. This way you can, for example, have a Button widget used for music with a music icon instead of the default.

**Comment by swttt** [comment]
Would make this possible by integrating it into the wizard steps.
This would make it available to all the device widgets, so you can change the icons for some dim spots as well :)

**Comment by swttt** [comment]
Done in current Alpha
