### ISSUE TITLE
[Enhancement] Disable (vertical) scrolling when not needed on dashboard page. 

### ISSUE THREAD

**Issue by Qx5** [swttt/com.swttt.homeydash#36]
Sometimes (nonchalant) clicking on the dashboard results in a vertical scroll instead of the click you wanted. When the amount of widgets does not require scrolling it would be nice if this would be disabled. 

Issue experienced on ipad mini 1st gen

**Comment by swttt** [comment]
Current way of handeling widget heights should fix this i think...could you test the current alpha and report back?

**Comment by swttt** [comment]
Just thought about it... this might be the rubber band scrolling on ios :/
Not something that can be fixed nicely...

**Comment by Qx5** [comment]
Shit I think you're right. 
You probably already searched but might this help?;
http://stackoverflow.com/questions/37586286/prevent-overflow-rubberband-scrolling-on-ios

**Comment by swttt** [comment]
You tried the current Alpha? Since i added a jquery scroll for the iOS issues i was having earlier. This takes a longer swipe to get the rubber band. Might fix it as well.

**Comment by swttt** [comment]
Should be fixed now, re-open please if not :)

**Comment by Qx5** [comment]
Rubber band scrolling still seems as sensitive to me. 

But actually now the whole widgets are clickable it feels like less as an issue to me because it feels easier to click now.  Would be nice if it could get disabled anyhow but if IOS makes this really hard then don't put the effort in it :)
