### ISSUE TITLE
Feature Request: Sort cards in settings page

### ISSUE THREAD

**Issue by spoelly** [swttt/com.swttt.homeydash#4]
It would be nice to sort the cards in the settings page

**Comment by swttt** [comment]
Something i need to add later, since it's quite complicated to handle this the right way.
Best way should be using a drag and drop list, but this also has to be touch compatible.

**Comment by spoelly** [comment]
No problem 😉 But now it's on your list

**Comment by swttt** [comment]
Done on 0.0.5
